import './globals.css';
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from './components/Sidebar';
import Header from './components/Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="flex w-full min-h-screen bg-gray-50">
        <Sidebar />
        <div className="flex flex-1 min-h-screen">
          <main className="flex-1 px-8 py-5">
            <Header />
            {children}</main>
        </div>
      </body>
    </html>
  );
}

