import './globals.css';
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="flex h-screen bg-gray-50">
          {children}
      </body>
    </html>
  );
}


